<?php

namespace AppBundle\Repository;

/**
 * AppConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppConfigRepository extends \Doctrine\ORM\EntityRepository
{
}
