<?php

namespace AppBundle\Repository;

/**
 * StoreCredentialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoreCredentialRepository extends \Doctrine\ORM\EntityRepository
{
}
