<?php

namespace AppBundle\Repository;

/**
 * StoreProductReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoreProductReviewRepository extends \Doctrine\ORM\EntityRepository
{
}
