# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: sha512
            iterations: 1
            encode_as_base64: false
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        # main:
        #     entity:
        #         class: AppBundle\Entity\User
        main:
            entity:
                class: AppBundle:User
                property: username
                # property: username
        api_key_user_provider:
            id: api_key_user_provider

    role_hierarchy:
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api/v1
            stateless: true
            simple_preauth:
                authenticator: apikey_authenticator
            provider: api_key_user_provider
        # main:
        #     anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://securityymfony.com/doc/current/cookbook/security/form_login_setup.html
        security_area:
            pattern: ^/
            # provider: user_provider
            anonymous: ~    
            form_login:
                login_path: app_login
                check_path: app_login
                # always_use_default_target_path: false
                # # use_referer: true
                default_target_path: app_dashboard
                # remember_me: false
                failure_path: app_login
            logout:
                path:   app_auth_logout
                target: app_login
    access_control:
        # admin_login:
        #     path: /admin
        #     roles: IS_AUTHENTICATED_ANONYMOUSLY
        # admin_area:
        #     path: /admin/.*
        #     roles: ROLE_ADMIN
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/auth/app/install, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/auth/app/load, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/auth/app/uninstall, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: [ROLE_ADMIN, ROLE_USER] }



