app_dashboard:
    path: /
    defaults: {_controller: AppBundle:App:dashboard}

app_settings:
    path: /settings
    defaults: {_controller: AppBundle:App:setting}

app_manage_widget:
    path: /widget
    defaults: {_controller: AppBundle:App:widget}

app_login:
    path: /login
    defaults: {_controller: AppBundle:Auth:login}