AppBundle\Entity\AppConfig:
    type: entity
    table: app_config
    repositoryClass: AppBundle\Repository\AppConfigRepository
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
  
    fields:
        widgetTheme:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
        dateCreated:
            type: datetime
            columnDefinition: TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    oneToOne:
      user:
        targetEntity: AppBundle\Entity\User
        mappedBy: appConfig