AppBundle\Entity\StoreCredential:
    type: entity
    table: store_credentials
    repositoryClass: AppBundle\Repository\StoreCredentialRepository
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
  
    fields:
        accessToken:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        apiKey:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        scope:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        context:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        storeUser:
            type: string
            nullable: false
            length: 70
            fixed: false
            comment: ''
        dateCreated:
            type: datetime
            columnDefinition: TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    oneToOne:
      user:
        targetEntity: AppBundle\Entity\User
        mappedBy: authCredentials
    
